  
name: Move assigned card
on:
  pull_request_target:
    types: [ready_for_review]
jobs:
  moveCard:
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v1
        with:
          token: ${{ secrets.MARTIN_TOKEN }}
          project-location: databeacon
          project-name: Automation testing
          column-name: Review in progress
