#https://github.com/marketplace/actions/automate-projects

name: Move assigned card
on:
  issues:
    types: [assigned]
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
    
      - name: move-issues-when-assigned
        uses: docker://takanabe/github-actions-automate-projects:v0.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.MARTIN_TOKEN }}
          GITHUB_PROJECT_URL: https://github.com/orgs/databeacon/projects/5
          GITHUB_PROJECT_COLUMN_NAME: In progress
