#https://github.com/marketplace/actions/assign-to-one-project
name: Auto Assign (issues) to Project(s)

on:
  issues:
    types: [opened, assigned]
#  pull_request_target:
#    types: [opened, labeled]
env:
  MY_GITHUB_TOKEN: ${{ secrets.MARTIN_TOKEN }}

jobs:
  issues_handler:
    runs-on: ubuntu-latest
    name: Issues Handling Tasks
    
    steps:
    - name: Assign NEW issues to project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/orgs/databeacon/projects/5'
        column_name: 'To do'
        
    - name: Move issues when assigned to a person
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/orgs/databeacon/projects/5'
        column_name: 'In progress'
