#https://github.com/marketplace/actions/assign-to-one-project
name: Auto Assign (issues) to Project(s)

on:
  issues:
    types: [opened]

env:
  MY_GITHUB_TOKEN: ${{ secrets.GH_AUTOMATION_TOKEN }}
  status_draft: 📄 Draft
  status_planned: 📆 Planned
  label_epic: 👾 epic

jobs:
  open_issue:
    runs-on: ubuntu-latest
    name: Issues Handling Tasks
    steps:
    - name: Assign NEW issues to project
      uses: leonsteinhaeuser/project-beta-automations@v1.2.1
      if: github.event.action == 'opened'
      with:
        gh_token: ${{ env.MY_GITHUB_TOKEN }}
        organization: databeacon
        project_id: 12
        resource_node_id: ${{ github.event.issue.node_id }}
        status_value: ${{ env.status_planned }}

  open_epic:
    runs-on: ubuntu-latest
    name: Open EPIC
    steps:
    - name: Assign new EPIC to project
      uses: leonsteinhaeuser/project-beta-automations@v1.2.1
      if: github.event.action == 'opened' && (github.event.label.name == ${{ env.label_epic }})
      with:
        gh_token: ${{ env.MY_GITHUB_TOKEN }}
        organization: databeacon
        project_id: 12
        resource_node_id: ${{ github.event.issue.node_id }}
        status_value: ${{ env.status_planned }}


